Added Query Plan Telemetry
microsoft/vscode-mssql pull request #18303
Opened 2024-10-22 18:37 UTC by laurennat

Added  a telemetry point for opening query plans

2024-10-22 19:43 UTC, Benjin requested changes

2024-10-22 19:43 UTC, Benjin commented on src/queryResult/queryResultWebViewController.ts
> +                sendActionEvent(
`sendErrorEvent` for errors; also add metrics

2024-10-22 19:43 UTC, Benjin commented on src/queryResult/queryResultWebViewController.ts
> +        sendActionEvent(
`sendActionEvent`) (and `sendErrorEvent()`) both have optional props that can be set: `additionalMeasurements` (most numeric metrics) and `additionalProperties` (everything else).

Capturing something like the number of plans as a metric here would be good so we can see if, say, people are frequently viewing plans for 25 queries at once, or if we always get errors when it hits some threshold.

2024-10-22 19:43 UTC, Benjin commented on src/controllers/executionPlanWebviewController.ts
> +        );
sending an event at the beginning can be useful, but we generally care more about the end state: did it succeed or fail?  if it failed, what error did we get?  how many execution plans were in the XML?  how long did generating the plan from the XML take?

2024-10-25 18:02 UTC, laurennat commented
Closing this PR; I'm adding the telemetry changes with my other pr that addresses query plan issues

2024-10-25 18:02 UTC, closed without merging